version: '3'
services:
  db:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
  web:
    build: .
    volumes:
      - .:/var/opt/app/letshang
    command: rails server
    ports:
      - "3000:3000"
    depends_on:
      - db
